### PR TITLE
Add 2023-02 release and make the dockerfiles arch independent

### PR DESCRIPTION
**Pull request by autoantwort**

### CODE REVIEW

**Comment by gorenje** [comment]
Sweet 👍 Looks good to me :)

Thanks for the work!

**Comment by PatrickF-mbse** [comment]
@gorenje 
@autoantwort 

Hi,

Thank you very much for sharing this new version. I increase the memory on my docker Desktop and the Makefile execution went further than last week. I think the compose is the last step.

I got this error:  **'SYSML_RELEASE' is not recognized as an internal or external command,**
at  **SYSML_RELEASE=2023-02 RELEASE=2023-02 docker compose -f docker-compose.yml up.**

It seems it is confusing SYSML_RELEASE with a command. Starting to learn how docker works and if I understood well, SYSML_RELEASE is a string variable?   

Should this line be RELEASE=2023-02 docker compose -f docker-compose.yml up?   ie SYSML_RELEASE=2023-02 is a duplicate typo or a command is missing before  SYSML_RELEASE=2023-02?








docker build -t sysml.api:2023-02 -f Dockerfile.api --build-arg RELEASE=2023-02 .
[+] Building 340.4s (21/21) FINISHED
 => [internal] load build definition from Dockerfile.api                                                                                                                                          0.0s 
 => => transferring dockerfile: 2.14kB                                                                                                                                                            0.0s 
 => [internal] load .dockerignore                                                                                                                                                                 0.0s 
 => => transferring context: 2B                                                                                                                                                                   0.0s 
 => [internal] load metadata for docker.io/library/openjdk:11-slim                                                                                                                                1.4s 
 => [ 1/17] FROM docker.io/library/openjdk:11-slim@sha256:868a4f2151d38ba6a09870cec584346a5edc8e9b71fde275eb2e0625273e2fd8                                                                        0.0s 
 => CACHED [ 2/17] RUN apt-get --quiet --yes update && apt-get install -yqq wget                                                                                                                  0.0s 
 => CACHED [ 3/17] RUN adduser --disabled-password     --gecos "Default user"     --uid 1000     sysml                                                                                            0.0s 
 => CACHED [ 4/17] RUN chown -R 1000 /home/sysml                                                                                                                                                  0.0s 
 => CACHED [ 5/17] WORKDIR /home/sysml                                                                                                                                                            0.0s 
 => CACHED [ 6/17] RUN wget -q https://github.com/sbt/sbt/releases/download/v1.2.8/sbt-1.2.8.tgz                                                                                                  0.0s 
 => [ 7/17] RUN wget -q https://github.com/Systems-Modeling/SysML-v2-API-Services/archive/2023-02.tar.gz?ts=20220819Z020300+00 -O 2023-02.tar.gz                                                  2.4s 
 => [ 8/17] RUN tar xfz sbt-1.2.8.tgz                                                                                                                                                             1.0s 
 => [ 9/17] RUN tar xfz 2023-02.tar.gz                                                                                                                                                            0.9s 
 => [10/17] WORKDIR /home/sysml/SysML-v2-API-Services-2023-02                                                                                                                                     0.1s 
 => [11/17] RUN /home/sysml/sbt/bin/sbt clean                                                                                                                                                   176.0s 
 => [12/17] RUN /home/sysml/sbt/bin/sbt update                                                                                                                                                   81.0s 
 => [13/17] RUN /home/sysml/sbt/bin/sbt compile                                                                                                                                                  73.7s 
 => [14/17] RUN sed s/key=.whatever./key="longersecretnowarnings"/ -i conf/application.conf                                                                                                       0.4s 
 => [15/17] RUN echo "\n\nplay.filters.hosts {\n   allowed = ["sysmlapiserver:9000", "localhost:9000"]\n}\n" >> conf/application.conf                                                             0.4s 
 => [16/17] RUN sed s/localhost:5432/postgresdbserver:5432/ -i conf/META-INF/persistence.xml                                                                                                      0.4s 
 => [17/17] RUN sed s/value=.create-drop./value="update"/ -i conf/META-INF/persistence.xml                                                                                                        0.4s 
 => exporting to image                                                                                                                                                                            2.2s 
 => => exporting layers                                                                                                                                                                           2.2s 
 => => writing image sha256:d97961fd9db56d9ea8fa96214938db43ad73f5c4e7c40086f01380bcd33739d7                                                                                                      0.0s 
 => => naming to docker.io/library/sysml.api:2023-02                                                                                                                                              0.0s 
SYSML_RELEASE=2023-02 RELEASE=2023-02 docker compose -f docker-compose.yml up
'SYSML_RELEASE' is not recognized as an internal or external command,
operable program or batch file.
Makefile:24: recipe for target 'spin-up' failed
mingw32-make: *** [spin-up] Error 1

**Comment by gorenje** [comment]
that seems to be an issue of the underlying shell you're using - ming.

The command line (from the [Makefile](https://github.com/gorenje/sysmlv2-jupyter-docker/blob/caee0513e9995622270edf599c28d0f23aa4f88a/Makefile#L24)):
```
SYSML_RELEASE=2023-02 RELEASE=2023-02 docker compose -f docker-compose.yml up
```
is a perfectly fine unix shell command line. It's short for:
```
export SYSML_RELEASE=2023-02
export RELEASE=2023-02 
docker compose -f docker-compose.yml up
unset SYSML_RELEASE
unset RELEASE
```

try the above and see if you get further.

btw please don't post further comments here, rather over at the [issue](https://github.com/gorenje/sysmlv2-jupyter-docker/issues/10).

**Comment by PatrickF-mbse** [comment]
UPDATE:
I replaced the line with:
$env:SYSML_RELEASE="2023-02"; $env:RELEASE="2023-02"; docker compose -f docker-compose.yml up using Mr ChatGPT advice and it worked. Not sure if this is due to the fact that I am using windows. my docker compose version is Docker Compose version v2.17.3.

Do you want me to post this in the issues as a tip for windows 10 + Docker station users trying to run makefile?

**Pull request merged**
