### PR TITLE
Added uninstall of python kernel

### PR DESCRIPTION
**Pull request by Weilkiti**
The python kernel is used by hackers to run mining scripts on the server.

It would be great to also change a kernel spec setting, but I don't know how to update the config file in the dockerfile. The setting can also be set when starting the jupyter lab:

jupyter lab --KernelSpecManager.ensure_native_kernel=False

### CODE REVIEW

**Comment by gorenje** [comment]
I'm not sure I want to do this since there is a test suite generator - https://github.com/gorenje/sysmlv2-jupyter-docker/blob/main/notebooks/gorenje/TestSuiteGenerator.ipynb - notebook that generates a number of other notebooks. That would no longer work with this change since it uses the python engine.

I'll investigate whether that is in fact the case.

Cheers!

**Comment by Weilkiti** [comment]
Ok – alternatively, I could create a fork or branch of the repository for a sysmlv2lab.com version. Currently, I cannot run the server anymore, because it is hijacked by coin miners. What do you think?

Cheers,
Tim

**Comment by gorenje** [comment]
What we can do here is create a completely new Dockerfile that creates a complete new docker image that you can use - so avoid creating a fork, perhaps it's better to have Dockerfile.nonpy3 (that is a clone of Dockerfile.hub) that generates a new image.

This would then generate a new docker hub image i.e. using https://github.com/gorenje/sysmlv2-jupyter-docker/blob/main/.github/workflows/2022-04.dockerpush.yml as a basis and then add new tag ... something like gorenje/sysmlv2-jupyter-nonpy:2022-04

Just a suggestion

**Comment by Weilkiti** [comment]
Sounds good!

Any idea about how to set the setting KernelSpecManager.ensure_native_kernel=False during the installation process?

**Comment by gorenje** [comment]
I think you're looking for https://github.com/gorenje/sysmlv2-jupyter-docker/blob/main/scripts/hub.sh - this is the start script for [Dockerfile.hub](https://github.com/gorenje/sysmlv2-jupyter-docker/blob/main/Dockerfile.hub#L91-L97) image.

**Comment by Weilkiti** [comment]
Yes, that seems to be the right location. The call of jupyter lab should be:

jupyter lab --ip 0.0.0.0 --port 8888 --no-browser --KernelSpecManager.ensure_native_kernel=False

Can you add it or should I create a new pull request?

**Comment by gorenje** [comment]
Use the power of the pull! ;)

**Comment by gorenje** [comment]
If this doesn't break my [TestSuiteGenerator](https://github.com/gorenje/sysmlv2-jupyter-docker/blob/main/notebooks/gorenje/TestSuiteGenerator.ipynb) notebook, I'll merge. But I'll check that first.

Cheers!

**Comment by Weilkiti** [comment]
Done

**Comment by gorenje** [comment]
Ok it seems this does not affect the test suite.

**Comment by Weilkiti** [comment]
Great - the sysmlv2lab.com is up and running again. Let's cross our fingers that miners will not find another leak.

**Pull request merged**
